<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
       $permissions = [
    ['id' => 1, 'name' => 'dashboard.view', 'group' => 'dashboard'],
    ['id' => 2, 'name' => 'users.view', 'group' => 'users'],
    ['id' => 3, 'name' => 'users.create', 'group' => 'users'],
    ['id' => 4, 'name' => 'users.edit', 'group' => 'users'],
    ['id' => 5, 'name' => 'users.delete', 'group' => 'users'],
    ['id' => 6, 'name' => 'users.toggle_status', 'group' => 'users'],
    ['id' => 7, 'name' => 'users.change_password', 'group' => 'users'],
    ['id' => 8, 'name' => 'roles.view', 'group' => 'roles'],
    ['id' => 9, 'name' => 'roles.create', 'group' => 'roles'],
    ['id' => 10, 'name' => 'roles.edit', 'group' => 'roles'],
    ['id' => 11, 'name' => 'roles.delete', 'group' => 'roles'],
    ['id' => 12, 'name' => 'roles.assign', 'group' => 'roles'],
    ['id' => 13, 'name' => 'vehicles.view', 'group' => 'vehicles'],
    ['id' => 14, 'name' => 'vehicles.create', 'group' => 'vehicles'],
    ['id' => 15, 'name' => 'vehicles.edit', 'group' => 'vehicles'],
    ['id' => 16, 'name' => 'vehicles.delete', 'group' => 'vehicles'],
    ['id' => 17, 'name' => 'vendors.view', 'group' => 'vendors'],
    ['id' => 18, 'name' => 'vendors.create', 'group' => 'vendors'],
    ['id' => 19, 'name' => 'vendors.edit', 'group' => 'vendors'],
    ['id' => 20, 'name' => 'vendors.delete', 'group' => 'vendors'],
    ['id' => 21, 'name' => 'clients.view', 'group' => 'clients'],
    ['id' => 22, 'name' => 'clients.create', 'group' => 'clients'],
    ['id' => 23, 'name' => 'clients.edit', 'group' => 'clients'],
    ['id' => 24, 'name' => 'clients.delete', 'group' => 'clients'],
    ['id' => 25, 'name' => 'drivers.view', 'group' => 'drivers'],
    ['id' => 26, 'name' => 'drivers.create', 'group' => 'drivers'],
    ['id' => 27, 'name' => 'drivers.edit', 'group' => 'drivers'],
    ['id' => 28, 'name' => 'drivers.delete', 'group' => 'drivers'],
    ['id' => 29, 'name' => 'StateNameWithCode.view', 'group' => 'StateNameWithCode'],
    ['id' => 30, 'name' => 'StateNameWithCode.create', 'group' => 'StateNameWithCode'],
    ['id' => 31, 'name' => 'StateNameWithCode.edit', 'group' => 'StateNameWithCode'],
    ['id' => 32, 'name' => 'StateNameWithCode.delete', 'group' => 'StateNameWithCode'],
    ['id' => 33, 'name' => 'Gstrate.view', 'group' => 'Gstrate'],
    ['id' => 34, 'name' => 'Gstrate.create', 'group' => 'Gstrate'],
    ['id' => 35, 'name' => 'Gstrate.edit', 'group' => 'Gstrate'],
    ['id' => 36, 'name' => 'Gstrate.delete', 'group' => 'Gstrate'],
    ['id' => 37, 'name' => 'Fuel.view', 'group' => 'Fuel'],
    ['id' => 38, 'name' => 'Fuel.create', 'group' => 'Fuel'],
    ['id' => 39, 'name' => 'Fuel.edit', 'group' => 'Fuel'],
    ['id' => 40, 'name' => 'Fuel.delete', 'group' => 'Fuel'],
    ['id' => 41, 'name' => 'Yearmaster.view', 'group' => 'Yearmaster'],
    ['id' => 42, 'name' => 'Yearmaster.create', 'group' => 'Yearmaster'],
    ['id' => 43, 'name' => 'Yearmaster.edit', 'group' => 'Yearmaster'],
    ['id' => 44, 'name' => 'Yearmaster.delete', 'group' => 'Yearmaster'],
    ['id' => 45, 'name' => 'YearmasterStatus.create', 'group' => 'Yearmaster'],
    ['id' => 46, 'name' => 'Yearmaster.status', 'group' => 'Yearmaster'],
    ['id' => 47, 'name' => 'selfVehicle.view', 'group' => 'selfVehicle'],
    ['id' => 48, 'name' => 'selfVehicle.create', 'group' => 'selfVehicle'],
    ['id' => 49, 'name' => 'selfVehicle.edit', 'group' => 'selfVehicle'],
    ['id' => 50, 'name' => 'selfVehicle.delete', 'group' => 'selfVehicle'],
    ['id' => 51, 'name' => 'TripMovement.view', 'group' => 'TripMovement'],
    ['id' => 52, 'name' => 'TripMovement.create', 'group' => 'TripMovement'],
    ['id' => 53, 'name' => 'TripMovement.edit', 'group' => 'TripMovement'],
    ['id' => 54, 'name' => 'TripMovement.delete', 'group' => 'TripMovement'],
    ['id' => 55, 'name' => 'BankRegister.view', 'group' => 'BankRegister'],
    ['id' => 56, 'name' => 'BankRegister.create', 'group' => 'BankRegister'],
    ['id' => 57, 'name' => 'BankRegister.edit', 'group' => 'BankRegister'],
    ['id' => 58, 'name' => 'BankRegister.delete', 'group' => 'BankRegister'],
    ['id' => 59, 'name' => 'Vouchermaster.view', 'group' => 'Vouchermaster'],
    ['id' => 60, 'name' => 'Vouchermaster.create', 'group' => 'Vouchermaster'],
    ['id' => 61, 'name' => 'Vouchermaster.edit', 'group' => 'Vouchermaster'],
    ['id' => 62, 'name' => 'Vouchermaster.delete', 'group' => 'Vouchermaster'],
    ['id' => 63, 'name' => 'Attendancemanagement.view', 'group' => 'Attendancemanagement'],
    ['id' => 64, 'name' => 'Attendancemanagement.create', 'group' => 'Attendancemanagement'],
    ['id' => 65, 'name' => 'Attendancemanagement.edit', 'group' => 'Attendancemanagement'],
    ['id' => 66, 'name' => 'Attendancemanagement.delete', 'group' => 'Attendancemanagement'],
    ['id' => 67, 'name' => 'Companyprofile.view', 'group' => 'Companyprofile'],
    ['id' => 68, 'name' => 'Companyprofile.create', 'group' => 'Companyprofile'],
    ['id' => 69, 'name' => 'Companyprofile.edit', 'group' => 'Companyprofile'],
    ['id' => 70, 'name' => 'Companyprofile.delete', 'group' => 'Companyprofile'],
    ['id' => 71, 'name' => 'ContactList.view', 'group' => 'ContactList'],
    ['id' => 72, 'name' => 'ContactList.create', 'group' => 'ContactList'],
    ['id' => 73, 'name' => 'ContactList.edit', 'group' => 'ContactList'],
    ['id' => 74, 'name' => 'ContactList.delete', 'group' => 'ContactList'],
    ['id' => 75, 'name' => 'Employeemanagement.view', 'group' => 'Employeemanagement'],
    ['id' => 76, 'name' => 'Employeemanagement.create', 'group' => 'Employeemanagement'],
    ['id' => 77, 'name' => 'Employeemanagement.edit', 'group' => 'Employeemanagement'],
    ['id' => 78, 'name' => 'Employeemanagement.delete', 'group' => 'Employeemanagement'],
    ['id' => 79, 'name' => 'Groupandledgermaster.view', 'group' => 'Groupandledgermaster'],
    ['id' => 80, 'name' => 'Groupandledgermaster.create', 'group' => 'Groupandledgermaster'],
    ['id' => 81, 'name' => 'Groupandledgermaster.edit', 'group' => 'Groupandledgermaster'],
    ['id' => 82, 'name' => 'Groupandledgermaster.delete', 'group' => 'Groupandledgermaster'],
    ['id' => 83, 'name' => 'Payrollpaymentmanagement.view', 'group' => 'Payrollpaymentmanagement'],
    ['id' => 84, 'name' => 'Payrollpaymentmanagement.create', 'group' => 'Payrollpaymentmanagement'],
    ['id' => 85, 'name' => 'Payrollpaymentmanagement.edit', 'group' => 'Payrollpaymentmanagement'],
    ['id' => 86, 'name' => 'Payrollpaymentmanagement.delete', 'group' => 'Payrollpaymentmanagement'],
    ['id' => 87, 'name' => 'Payrollslip.view', 'group' => 'Payrollslip'],
    ['id' => 88, 'name' => 'Payrollslip.create', 'group' => 'Payrollslip'],
    ['id' => 89, 'name' => 'Payrollslip.edit', 'group' => 'Payrollslip'],
    ['id' => 90, 'name' => 'Payrollslip.delete', 'group' => 'Payrollslip'],
    ['id' => 91, 'name' => 'Profilesetting.view', 'group' => 'Profilesetting'],
    ['id' => 92, 'name' => 'Profilesetting.create', 'group' => 'Profilesetting'],
    ['id' => 93, 'name' => 'Profilesetting.edit', 'group' => 'Profilesetting'],
    ['id' => 94, 'name' => 'Profilesetting.delete', 'group' => 'Profilesetting'],
    ['id' => 95, 'name' => 'Salaryreport.view', 'group' => 'Salaryreport'],
    ['id' => 96, 'name' => 'Salaryreport.create', 'group' => 'Salaryreport'],
    ['id' => 97, 'name' => 'Salaryreport.edit', 'group' => 'Salaryreport'],
    ['id' => 98, 'name' => 'Salaryreport.delete', 'group' => 'Salaryreport'],
    ['id' => 99, 'name' => 'TaxOnsalaryreport.view', 'group' => 'TaxOnsalaryreport'],
    ['id' => 100, 'name' => 'TaxOnsalaryreport.create', 'group' => 'TaxOnsalaryreport'],
    ['id' => 101, 'name' => 'TaxOnsalaryreport.edit', 'group' => 'TaxOnsalaryreport'],
    ['id' => 102, 'name' => 'TaxOnsalaryreport.delete', 'group' => 'TaxOnsalaryreport'],
    ['id' => 103, 'name' => 'VendorHasVehicle.view', 'group' => 'VendorHasVehicle'],
    ['id' => 104, 'name' => 'VendorHasVehicle.create', 'group' => 'VendorHasVehicle'],
    ['id' => 105, 'name' => 'VendorHasVehicle.edit', 'group' => 'VendorHasVehicle'],
    ['id' => 106, 'name' => 'VendorHasVehicle.delete', 'group' => 'VendorHasVehicle'],
    ['id' => 107, 'name' => 'CashMemo.view', 'group' => 'CashMemo'],
    ['id' => 108, 'name' => 'CashMemo.create', 'group' => 'CashMemo'],
    ['id' => 109, 'name' => 'CashMemo.edit', 'group' => 'CashMemo'],
    ['id' => 110, 'name' => 'CashMemo.delete', 'group' => 'CashMemo'],
    ['id' => 111, 'name' => 'TaxInvoice.view', 'group' => 'TaxInvoice'],
    ['id' => 112, 'name' => 'TaxInvoice.create', 'group' => 'TaxInvoice'],
    ['id' => 113, 'name' => 'TaxInvoice.edit', 'group' => 'TaxInvoice'],
    ['id' => 114, 'name' => 'TaxInvoice.delete', 'group' => 'TaxInvoice'],
    ['id' => 115, 'name' => 'ProfitandLossStmt.view', 'group' => 'ProfitandLossStmt'],
    ['id' => 116, 'name' => 'ProfitandLossStmt.create', 'group' => 'ProfitandLossStmt'],
    ['id' => 117, 'name' => 'ProfitandLossStmt.edit', 'group' => 'ProfitandLossStmt'],
    ['id' => 118, 'name' => 'ProfitandLossStmt.delete', 'group' => 'ProfitandLossStmt'],
    ['id' => 119, 'name' => 'LedgerStmt.view', 'group' => 'LedgerStmt'],
    ['id' => 120, 'name' => 'LedgerStmt.create', 'group' => 'LedgerStmt'],
    ['id' => 121, 'name' => 'LedgerStmt.edit', 'group' => 'LedgerStmt'],
    ['id' => 122, 'name' => 'LedgerStmt.delete', 'group' => 'LedgerStmt'],
    ['id' => 123, 'name' => 'BalancesheetStmt.view', 'group' => 'BalancesheetStmt'],
    ['id' => 124, 'name' => 'BalancesheetStmt.create', 'group' => 'BalancesheetStmt'],
    ['id' => 125, 'name' => 'BalancesheetStmt.edit', 'group' => 'BalancesheetStmt'],
    ['id' => 129, 'name' => 'BalancesheetStmt.delete', 'group' => 'BalancesheetStmt'],
];


        foreach ($permissions as $permission) {
            Permission::updateOrCreate([
                'id' => $permission['id']
            ], [
                'id' => $permission['id'],
                'name' => $permission['name'],
                'group' => $permission['group']
            ]);
        }
    }
}
